name: Build Documentation Pages

on:
  workflow_call:
    inputs:
      upload_artifact:
        description: "Whether to upload build artifact"
        required: false
        default: false
        type: boolean
    secrets:
      TALENT_PROTOCOL_API_KEY:
        required: true
  pull_request:
    branches:
      - main
    types: [ready_for_review, opened, reopened, synchronize]

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    env:
      TALENT_PROTOCOL_API_KEY: ${{ secrets.TALENT_PROTOCOL_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: OpenAPI Clean and Generate Documents
        run: |
          npm run generate-docs
      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
